config/routes.rb
Lodgework::Application.routes.draw do
  
  resources :communes

  resources :homes

  devise_for :users

  resources :users

  root :to => "homes#index"

end

app/models/commune.rb
class Commune < ActiveRecord::Base
  has_many :users
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  belongs_to :commune
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/communes_controller.rb
class CommunesController < ApplicationController
  # GET /communes
  # GET /communes.xml
  def index
    @communes = Commune.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @communes }
    end
  end

  # GET /communes/1
  # GET /communes/1.xml
  def show
    @commune = Commune.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @commune }
    end
  end

  # GET /communes/new
  # GET /communes/new.xml
  def new
    @commune = Commune.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @commune }
    end
  end

  # GET /communes/1/edit
  def edit
    @commune = Commune.find(params[:id])
  end

  # POST /communes
  # POST /communes.xml
  def create
    @commune = Commune.new(params[:commune])

    respond_to do |format|
      if @commune.save
        format.html { redirect_to(@commune, :notice => 'Commune was successfully created.') }
        format.xml  { render :xml => @commune, :status => :created, :location => @commune }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @commune.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /communes/1
  # PUT /communes/1.xml
  def update
    @commune = Commune.find(params[:id])

    respond_to do |format|
      if @commune.update_attributes(params[:commune])
        format.html { redirect_to(@commune, :notice => 'Commune was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @commune.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /communes/1
  # DELETE /communes/1.xml
  def destroy
    @commune = Commune.find(params[:id])
    @commune.destroy

    respond_to do |format|
      format.html { redirect_to(communes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.xml
  def index

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/communes/_form.html.erb
<%= form_for(@commune) do |f| %>
  <% if @commune.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commune.errors.count, "error") %> prohibited this commune from being saved:</h2>

      <ul>
      <% @commune.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :stretname %><br />
    <%= f.text_field :streetname %>
  </div>
  <div class="field">
    <%= f.label :streetnumber %><br />
    <%= f.text_field :streetnumber %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communes/edit.html.erb
<h1>Editing commune</h1>

<%= render 'form' %>

<%= link_to 'Show', @commune %> |
<%= link_to 'Back', communes_path %>

app/views/communes/index.html.erb
<h1>Listing communes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Streetname</th>
    <th>Streetnumber</th>
    <th>Zipcode</th>
    <th>City</th>
    <th>Country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @communes.each do |commune| %>
  <tr>
    <td><%= commune.name %></td>
    <td><%= commune.streetname %></td>
    <td><%= commune.streetnumber %></td>
    <td><%= commune.zipcode %></td>
    <td><%= commune.city %></td>
    <td><%= commune.country %></td>
    <td><%= link_to 'Show', commune %></td>
    <td><%= link_to 'Edit', edit_commune_path(commune) %></td>
    <td><%= link_to 'Destroy', commune, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Commune', new_commune_path %>

app/views/communes/new.html.erb
<h1>New commune</h1>

<%= render 'form' %>

<%= link_to 'Back', communes_path %>

app/views/communes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>String:</b>
  <%= @commune.name %>
</p>

<p>
  <b>String:</b>
  <%= @commune.streetname %>
</p>

<p>
  <b>String:</b>
  <%= @commune.streetnumber %>
</p>

<p>
  <b>String:</b>
  <%= @commune.zipcode %>
</p>

<p>
  <b>String:</b>
  <%= @commune.city %>
</p>

<p>
  <b>String:</b>
  <%= @commune.country %>
</p>

<p>
	<ul>
	<% @commune.users.each do |user| %>
	<li><%= user.email %></li>
	<% end %>
	</ul>
</p>


<%= link_to 'Edit', edit_commune_path(@commune) %> |
<%= link_to 'Back', communes_path %>

app/views/homes/index.html.erb
<h1>Hello world.</h1>

This is the main page.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lodgework</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

<ul class="hmenu">
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>